apiVersion: v1
kind: Secret
type: extauth.solo.io/apikey
metadata:
  name: infra-apikey
  namespace: gloo-system
  labels:
    team: test
data:
  api-key: TjJZd01ESXhaVEV0TkdVek5TMWpOemd6TFRSa1lqQXRZakUyWXpSa1pHVm1OamN5
  # Adding site key as metadata (base64 encoded)
  site-key: <add site key as base64 encoded>