apiVersion: v1
kind: ServiceAccount
metadata:
  name: recaptcha-client
---
apiVersion: v1
kind: Service
metadata:
  name: recaptcha-client
  labels:
    app: recaptcha-client
spec:
  ports:
    - name: http
      port: 8000
      targetPort: 8090
  selector:
    app: recaptcha-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recaptcha-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recaptcha-client
      version: v1
  template:
    metadata:
      labels:
        app: recaptcha-client
        version: v1
    spec:
      serviceAccountName: recaptcha-client
      containers:
        - name: recaptcha-client
          image: australia-southeast1-docker.pkg.dev/field-engineering-apac/public-repo/recaptcha-processor-test-client:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "8090"
            - name: CAPTCHA_SITE_KEY
              value: <add site key here>
            - name: BACKEND_HOST_API
              value: "http://192.168.106.224/submit"
            - name: API_KEY
              value: "N2YwMDIxZTEtNGUzNS1jNzgzLTRkYjAtYjE2YzRkZGVmNjcy"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: recaptcha-backend
---
apiVersion: v1
kind: Service
metadata:
  name: recaptcha-backend
  labels:
    app: recaptcha-backend
spec:
  ports:
    - name: http
      port: 8001
      targetPort: 8091
  selector:
    app: recaptcha-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recaptcha-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recaptcha-backend
      version: v1
  template:
    metadata:
      labels:
        app: recaptcha-backend
        version: v1
    spec:
      serviceAccountName: recaptcha-backend
      containers:
        - name: recaptcha-backend
          image: australia-southeast1-docker.pkg.dev/field-engineering-apac/public-repo/recaptcha-processor-test-backend-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
          env:
            - name: SERVER_HOST
              value: "0.0.0.0"
            - name: SERVER_PORT
              value: "8091"